### ISSUE TITLE
Add namespace to SCSS folders

### ISSUE THREAD

**Issue by javierarce** [CartoDB/CartoAssets#14]
The method we are going to use to import specific files from CartoAssets uses an entry file to load the SCSS (see for example the one for DeepInsights [here](https://github.com/CartoDB/deep-insights.js/blob/cartoassets/themes/scss/entry.scss))

In the following example, we are importing the sizes & mixins files from CartoAssets, but the developer could be mislead and think that those libraries come from the local project and not CartoAssets:

``` scss
// Variables and functions
@import 'variables/sizes';
@import 'utilities/mixins';
// Deep-insights styles
@import 'map/canvas';
@import 'map/dashboard-info';
```

I think it would make sense to add a namespace to the `variables`, `utilities`, etc. folders in order to avoid confusion.

We would have something like this instead:

``` scss
// Variables and functions
@import 'cdb-variables/sizes';
@import 'cdb-utilities/mixins';
// Deep-insights styles
@import 'map/canvas';
@import 'map/dashboard-info';
```

What do you think, @xavijam, @piensaenpixel, @matallo, & @viddo?

**Comment by viddo** [comment]
:+1: sounds reasonable to me, don't have much more to add ¯\_(ツ)_/¯

**Comment by xavijam** [comment]
I like the idea so :+1:

**Comment by matallo** [comment]
fine with me. Anyway I'm not doing so in commercial site as those folders are pretty generic and they won't grow in number

another thing I detected and works for me (maybe it's a different issue, and maybe adds a bit more of structure/complexity) is that instead of having the `map/...` in that entry file, have _another_ entry file for `widgets.scss`, `map.scss` with them listed

:+1:

**Comment by javierarce** [comment]
@matallo: that's a good idea. I guess if the file starts growing too much it'll make lot of sense.

Thanks, guys! I'll make the changes.

**Comment by matallo** [comment]
BOOM, delighted to contribute with some previous experience, keep pushing! :bow:
