### ISSUE TITLE
New style for check and radio buttons

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/CartoAssets#156]
Design issue: https://github.com/CartoDB/design/issues/472

![buttons](https://cloud.githubusercontent.com/assets/16247628/21804356/e173567a-d72e-11e6-8b7a-733e8f32c7d8.png)

Default and Disabled:

- [ ] Remove inner icon

Hover and Focus:

- [ ] Apply the border color to the icon

Selected stays the same

**Comment by piensaenpixel** [comment]
PR to review - https://github.com/CartoDB/CartoAssets/pull/157
