### ISSUE TITLE
Review components under Firefox

### ISSUE THREAD

**Issue by xavijam** [CartoDB/CartoAssets#34]
<img width="207" alt="screen shot 2016-01-28 at 09 45 39" src="https://cloud.githubusercontent.com/assets/132146/12639308/ef90db8a-c5a3-11e5-93eb-a7f2053e91f7.png">
<img width="193" alt="screen shot 2016-01-28 at 09 45 49" src="https://cloud.githubusercontent.com/assets/132146/12639309/f0d7c30a-c5a3-11e5-949b-d7fea246c319.png">
<img width="964" alt="screen shot 2016-01-28 at 09 45 46" src="https://cloud.githubusercontent.com/assets/132146/12639311/f36176f2-c5a3-11e5-8c91-8f62aa7b7b91.png">

**Comment by xavijam** [comment]
Assigned as you consider @piensaenpixel or @MariaCheca.

**Comment by MariaCheca** [comment]
Mine, I have to test it in IE 10 too.
