### ISSUE TITLE
Step component

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/CartoAssets#53]
![screen shot 2016-02-05 at 10 43 23](https://cloud.githubusercontent.com/assets/2141690/12842801/50b0e78c-cbf5-11e5-9c5d-aa4a74520221.png)

**Comment by piensaenpixel** [comment]
@MariaCheca two things.
- For me this structure is the same that we are using in header's component, so maybe we could reuse, what do you think?
- CDB-Step-headerNumeration I think is two pixels bigger, maybe we need add box-sizing.
