### ISSUE TITLE
Input range is not working properly in Chrome under Ubuntu OS

### ISSUE THREAD

**Issue by xavijam** [CartoDB/CartoAssets#82]
![pasted_image_at_2016_03_04_02_11_pm_720](https://cloud.githubusercontent.com/assets/132146/13528235/f316e28a-e214-11e5-9f64-5ba4c22df867.png)

cc @piensaenpixel

**Comment by piensaenpixel** [comment]
We know @AbelVM :( the last release of chrome broke it :(
So now... we need use jquery ui for this.

**Comment by MariaCheca** [comment]
Hey, is it still happening?

**Comment by AbelVM** [comment]
Yep. Chrome/Ubuntu here
